train:
  _target_: src.datasets.TableDataset
  path: data/csvs/adult_train.csv
  instance_transforms: ${transforms.instance_transforms.train}
  discrete_columns: ["workclass", "education", "marital-status", "occupation", "relationship", "race", "sex", "native-country", "income"]
