defaults:
  - model: ctgan
  - metrics: gan
  - datasets: adult
  - dataloader: ctgan
  - transforms: ctgan
  - _self_
inferencer_class:
  _target_: src.trainer.CTGANInferencer
inferencer:
  device_tensors: ["data_object", "labels", "cond", "mask"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "ctgan" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/ctgan/checkpoint-epoch500.pth" # path to the pretrained model
  number_of_samples: 32561
  target_class: "income"
  # type: 1
