defaults:
  - model: tgan
  - metrics: gan
  - datasets: adult
  - dataloader: default # placeholder
  - transforms: gan
  - _self_
inferencer_class:
  _target_: src.trainer.GANInferencer
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "tgan" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/tgan/model_best.pth" # path to the pretrained model
  target:
    0: 24720
    1: 7841
